server:
  port: 9000
app:
  datasource:
    jdbc-url: jdbc:mysql://172.21.3.49:3306/lab2
    username: bean
    password: beandev@123
spring:
  profiles:
    active: @spring.profiles.active@
  jpa:
    hibernate:
      ddl-auto: update
