server:
  port: 5000

app:
  datasource:
    jdbc-url: jdbc:postgresql://fullstackspringbootdb.c3hm0zwlqneg.ap-southeast-1.rds.amazonaws.com:5432/lab2
    username: postgres
    password: postgres

spring:
  profiles:
    active: @spring.profiles.active@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update