app:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/lab2
    username: bean
    password: beandev@123

spring:
  profiles:
    active: @spring.profiles.active@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 9000