app:
  datasource:
    jdbc-url: jdbc:mysql://lab2.c3hm0zwlqneg.ap-southeast-1.rds.amazonaws.com:3306/lab2
    username: admin
    password: password

spring:
  profiles:
    active: @spring.profiles.active@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 5000